* Notice

This is a work in progress. There's not a whole lot here yet.

Don't run this yet!
* What is Worgle?

Hello, fellow human. I'm glad you could stop by.

This is a document written
in Org markup, talking about a thing I'm building called Worgle. The name
*Worgle* is derived from what it is: a Worg Tangler. =Worg= is the name of this
project. It too gets its name from what it is: a WEB + Org project.
Org is the very decent markup language from org-mode.
WEB is
the name of the first literate programming tool ever created by Donald Knuth.
In literate programming,
one writes language and code together in a markup language, which can
then be parsed two ways. The *weaver* parses the markup to produce a
human readable document, usually a (La)TeX or HTML file. The *tangler*
parses the markup and produces computer code that can be read by a computer
to run or compile the program.

In other words, Worgle is a literate programming tangler used to convert
org-like markup into (primarily) code.

Worgle itself is a literate program, so what tangles the worgle code? Orgle
does! Orgle is a program written in C without literate programming. It is
designed to be just enough of a program to bootstrap Worgle. Worgle will
then be used as the tangler for the rest of Worg.

Worgle will initially start out as a literate program of Orgle. In fact,
this document will initially start out as an outline for the Orgle program.
The Orgle program will be considered done when it is able to produce a similar
program by parsing this Worgle document. After that is done, more work will
be put into Worgle to make it more suitable for managing larger projects
written in C.

Following me so far? No? Yes? Great, let's get started.
* Top-level files

Like Orgle, Worgle is self contained inside of a single C file.
For the time being, this is suitable enough. The current scope of Worgle is
to be a self-contained standalone CLI application.

#+NAME: worgle-top
#+BEGIN_SRC c :tangle worgle.c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

<<structs>>
<<function_declarations>>
<<functions>>

int main(int argc, char *argv[])
{
    printf("Sorry. No Worgling yet.\n");
    <<loading>>
    <<parsing>>
    <<generation>>
    return 0;
}

#+END_SRC
* An Outline of What Worgle does

This aims to show a broad overview of how Orgle (and Worgle) will work
essentially. Orgle is a bootstrap program written in C, used to generate
C code for Worgle (this program here). At the highest level, the two
programs share the same basic program structure.
** Load file into memory

The first thing the program will do is load the file.

While most parsers tend to parse things on a line by line basis via
a file stream, this parser will load the entire file into memory. This
is done due to the textual nature of the program. It is much easier to
simply allocate everything in one big block and reference chunks, then to
allocate smaller chunks as you go.

#+NAME:loading
#+BEGIN_SRC c

#+END_SRC
** Parsing

The second phase of the program is the parsing stage.

The parsing stage will parse files line-by-line. The program will find a line
by skimming through the block up to a line break character, then pass
that off to be parsed. Line by line, the parser will read the program and
produce a structure of the tangled code in memory.

#+NAME:parsing
#+BEGIN_SRC c

#+END_SRC
*** Reading a line at a time

Despite being loaded into memory, the program still reads in code one line
at a time. The parsing relies on new line feeds to denote the beginnings
and endings of sections and code references.

A special readline function has been written based on =getline= that reads
lines of text from an allocated block of text.
*** Parsing Modes

The parser is implemented as a relatively simple state machine, whose behavior
shifts between parsing org-mode markup (=MODE_ORG=), and code blocks
(=MODE_BEGINCODE= and =MODE_CODE=).
The state machine makes a distinction between the start of a new code
block (=MODE_BEGINCODE=), which provides information like the name of
the code block and optionally the name of the file to tangle to, and
the code block itself (=MODE_CODE=).
**** MODE_ORG

***** Extracting information from #+NAME

***** Beginning a new block

**** MODE_BEGINCODE

***** Extracting information from #+BEGIN_SRC

***** Setting up code for a new read

**** MODE_CODE

***** Checking for #+END_SRC

***** Checking for references
** Generation

The last phase of the program is code generation.

A parsed file generates a structure of how the code will look. The generation
stage involves iterating through the structure and producing the code.

Due to the hierarchical nature of the data structures,
the generation stage is surprisingly elegant with a single expanding entry
point.

At the very top, generation
consists of writing all the files in the filelist. Each file will then go
and write the top-most block associated with that file. A block will then
write the segment list it has embedded inside of it. A segment will either
write a string literal to disk, or a recursively expand block reference.

#+NAME:generation
#+BEGIN_SRC c

#+END_SRC

* Core Data Structures

The Worgle/Orgle program is very much a data-structure driven program.
Understanding the hierarchy of data here will provide a clear picture for
how the tangling works.

#+NAME: structs
#+BEGIN_SRC c
<<worgle_string>>
<<worgle_segment>>
<<worgle_block>>
<<worgle_blocklist>>
<<worgle_hashmap>>
<<worgle_file>>
<<worgle_filelist>>
#+END_SRC

** Top Level Struct

All Worgle operations are contained in a top-level struct called =worgle_d=.
For the most part, this struct aims to be dynamically populated inside of
[[An Outline of What Worgle does]].
** String
A string is a wrapper around a raw =char= pointer and a size. This is used
as the base string literal.

#+NAME: worgle_string
#+BEGIN_SRC c
typedef struct {
    char *str;
    size_t size;
} worgle_string;
#+END_SRC
*** Reset or initialize a string

Strings in worgle are reset with the function =worgle_string_reset=.

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_string_reset(worgle_string *str);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
void worgle_string_reset(worgle_string *str)
{
    str->str = NULL;
    str->size = 0;
}
#+END_SRC

A string being initialized is identical to a string being reset. The function
=worgle_string_init= is just a wrapper around =worgle_string_reset=.

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_string_init(worgle_string *str);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
void worgle_string_init(worgle_string *str)
{
    worgle_string_reset(str);
}
#+END_SRC
*** Writing a String

A string is written to a particular filehandle with the function
=worgle_string_write=.Worgle strings are *not* zero-terminated
and can't be used in functions like printf.


#+NAME: function_declarations
#+BEGIN_SRC c
int worgle_string_write(FILE *fp, worgle_string *str);
#+END_SRC

This function is a wrapper around a call to =fwrite=.

#+NAME: functions
#+BEGIN_SRC c
int worgle_string_write(FILE *fp, worgle_string *str)
{
    return fwrite(str->str, 1, str->size, fp);
}
#+END_SRC
** Segment

A segment turns a string into a linked list component that has a type.
A segment type flag can either be a text chunk or a reference.

#+NAME: worgle_segment
#+BEGIN_SRC c
enum {
<<worgle_segment_types>>
};
typedef struct worgle_segment {
    int type;
    worgle_string str;
    <<worgle_segment_line_control>>
    struct worgle_segment *nxt;
} worgle_segment;
#+END_SRC

Segments also keep track of where they are in the original org file.
This information can be used to generate line control preprocessor commands
for C/C++.

#+NAME: worgle_segment_line_control
#+BEGIN_SRC c
size_t linum;
worgle_string *filename;
#+END_SRC
*** Text Chunk Type

A text chunk is a literal string of text.

When a text chunk segment is processed, it gets written to file directly.

#+NAME: worgle_segment_types
#+BEGIN_SRC c
SEGTYPE_TEXT,
#+END_SRC
*** Reference Type

A reference contains a string reference to another block.

When a reference
segment gets processed, it looks up the reference and processes all the
segements in that code block.

#+NAME: worgle_segment_types
#+BEGIN_SRC c
SEGTYPE_REFERENCE
#+END_SRC
*** Writing a Segment

A segment is written to a file handle using the function =worgle_segment_write=.
In addition to taking in a filehandle and segment, a hashmap is also passed
in in the event that the segment is a reference.

On sucess, the function returns TRUE (1). On failure, FALSE (0).

#+NAME: function_declarations
#+BEGIN_SRC c
int worgle_segment_write(worgle_segment *s, worgle_hashmap *h, FILE *fp);
#+END_SRC

Every segment writes a pre-processor macro indicating where it is located
in the original orgle from. From there, things change depending on the
type. If the segment is a chunk of text (=SEGTYPE_TEXT=), then the string
is written. If the segment is a reference (=SEGTYPE_REFERENCE=), the
function attempts to look up a block and write it to disk.

#+NAME: functions
#+BEGIN_SRC c
int worgle_segment_write(worgle_segment *s, worgle_hashmap *h, FILE *fp)
{
    worgle_block *b;
    fprintf(fp, "#line %lu \"", s->linum);
    worgle_string_write(fp, s->filename);
    fprintf(fp, "\"\n");
    if(s->type == SEGTYPE_TEXT) {
        worgle_string_write(fp, &s->str);
    } else {
        if(!worgle_hashmap_find(h, &s->str, &b)) {
            fprintf(stderr, "Could not find reference segment '");
            worgle_string_write(stderr, &s->str);
            fprintf(stderr, "'\n");
            return 0;
        }
        return worgle_block_write(b, h, fp);
    }

    return 1;
}
#+END_SRC
** Code Block
A code block is a top-level unit that stores some amount of code. It is
made up of a list of segments. Every code block has a unique name.

#+NAME: worgle_block
#+BEGIN_SRC c
typedef struct worgle_block {
    int nsegs;
    worgle_segment *head;
    worgle_segment *tail;
    worgle_string name;
    struct worgle_block *nxt;
} worgle_block;
#+END_SRC
*** Initializing a code block

A worgle code block is initialized using the function =worgle_block_init=.

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_block_init(worgle_block *b);
#+END_SRC

The initialization will zero out all the variables related to the segment
linked list, as well as initialize the string holding the name of the block.

#+NAME: functions
#+BEGIN_SRC c
void worgle_block_init(worgle_block *b)
{
    b->nsegs = 0;
    b->head = NULL;
    b->tail = NULL;
    b->nxt = NULL;
    worgle_string_init(&b->name);
}
#+END_SRC
*** Freeing a code block
A code block is freed using the function =worgle_block_free=.

#+NAME:function_declarations
#+BEGIN_SRC c
void worgle_block_free(worgle_block *lst);
#+END_SRC

This function iterates through the segment linked list contained
inside the block, and frees each one. Since there is nothing to
free below a segment, the standard free function is called directly.

#+NAME: functions
#+BEGIN_SRC c
void worgle_block_free(worgle_block *lst)
{
    worgle_segment *s;
    worgle_segment *nxt;
    int n;
    s = lst->head;
    for(n = 0; n < lst->nsegs; n++) {
        nxt = s->nxt;
        free(s);
        s = nxt;
    }
}
#+END_SRC
*** Appending a segment to a code block

A generic segment is appended to a code block with the function.
=worgle_block_append_segment=.
The block =b=, name of the block =str=, and type =type= are mandatory parameters
which describe the segment. The location in the file is also required, so the
line number =linum= and name of file =filename= are also provided as well.
This function is called inside of a type-specific append function instead of
being called directly.


#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_block_append_segment(worgle_block *b,
                                worgle_string *str,
                                int type,
                                size_t linum,
                                worgle_string *filename);
#+END_SRC

It is worthwhile to note that it is in this function that a data
segment type gets allocated.

#+NAME: functions
#+BEGIN_SRC c
void worgle_block_append_segment(worgle_block *b,
                                worgle_string *str,
                                int type,
                                size_t linum,
                                worgle_string *filename)
{
    worgle_segment *s;
    s = malloc(sizeof(worgle_segment));
    s->str = *str;
    s->type = type;
    if(b->nsegs == 0) {
        b->head = s;
        b->tail = s;
    }
    s->linum = linum;
    s->filename = filename;
    b->tail->nxt = s;
    b->tail = s;
    b->nsegs++;
}
#+END_SRC

**** Appending a string segment

A string segment is appended to a code block using the function
=worgle_block_append_string=.

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_block_append_string(worgle_block *b,
                               worgle_string *str,
                               size_t linum,
                               worgle_string *filename);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
void worgle_block_append_string(worgle_block *b,
                               worgle_string *str,
                               size_t linum,
                               worgle_string *filename)
{
    worgle_block_append_segment(b, str, SEGTYPE_TEXT, linum, filename);
}
#+END_SRC
**** Appending a reference segment

A reference segment is appended to a code block using the function
=worgle_block_append_reference=.

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_block_append_reference(worgle_block *b,
                                  worgle_string *str,
                                  size_t linum,
                                  worgle_string *filename);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
void worgle_block_append_reference(worgle_block *b,
                                  worgle_string *str,
                                  size_t linum,
                                  worgle_string *filename)
{
    worgle_block_append_segment(b, str, SEGTYPE_REFERENCE, linum, filename);
}
#+END_SRC
*** Appending a code block to a code block

In both CWEB and Org-tangle, existing code blocks can be appeneded to in
different sections. Because of how this program works, we get this functionality
for free!
*** Writing a code block to filehandle

Writing a code block to a filehandle can be done using the function
=worgle_block_write=. In addition to the file handle =fp=, an org block
requires a hashmap, which is required in the lower level function
=orgle_segment_write= for expanding code references.

This function returns a boolean TRUE (1) on success or FALSE (0) on failure.

#+NAME: function_declarations
#+BEGIN_SRC c
int worgle_block_write(worgle_block *b, worgle_hashmap *h, FILE *fp);
#+END_SRC

A code block iterates it's segment list, writing each segment to disk.

#+NAME: functions
#+BEGIN_SRC c
int worgle_block_write(worgle_block *b, worgle_hashmap *h, FILE *fp)
{
    worgle_segment *s;
    int n;
    s = b->head;
    for(n = 0; n < b->nsegs; n++) {
        if(!worgle_segment_write(s, h, fp)) return 0;
        s = s->nxt;
    }

    return 1;
}
#+END_SRC

** Code Block List

A code block list is a linked list of blocks, which is used inside of a
hash map.
#+NAME: worgle_blocklist
#+BEGIN_SRC c
typedef struct {
    int nblocks;
    worgle_block *head;
    worgle_block *tail;
} worgle_blocklist;
#+END_SRC
*** Block List Initialization

A block list is initialized using the function =worgle_blocklist_init=.

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_blocklist_init(worgle_blocklist *lst);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
void worgle_blocklist_init(worgle_blocklist *lst)
{
    lst->head = NULL;
    lst->tail = NULL;
    lst->nblocks = 0;
}
#+END_SRC
*** Freeing a Block List

Blocks allocated by the block list are freed using the function
=worgle_blocklist_free=.

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_blocklist_free(worgle_blocklist *lst);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
void worgle_blocklist_free(worgle_blocklist *lst)
{
    worgle_block *b;
    worgle_block *nxt;
    int n;
    b = lst->head;
    for(n = 0; n < lst->nblocks; n++) {
        nxt = b->nxt;
        worgle_block_free(b);
        free(b);
        b = nxt;
    }
}
#+END_SRC
*** Appending a Block

An allocated block is appended to a block list using the function
=worgle_blocklist_append=.

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_blocklist_append(worgle_blocklist *lst, worgle_block *b);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
void worgle_blocklist_append(worgle_blocklist *lst, worgle_block *b)
{
    if(lst->nblocks == 0) {
        lst->head = b;
        lst->tail = b;
    }
    lst->tail->nxt = b;
    lst->tail = b;
    lst->nblocks++;
}
#+END_SRC
** Hash Map

A hash map is a key-value data structure used as a dictionary for storing
references to code blocks.
#+NAME: worgle_hashmap
#+BEGIN_SRC c
typedef struct {
    worgle_blocklist blk[256];
    int nwords;
} worgle_hashmap;
#+END_SRC
*** Hash map Initialization

A hash map is initialized using the function =worgle_hashmap_init=

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_hashmap_init(worgle_hashmap *h);
#+END_SRC

A hashmap is composed of an array of block lists which must be initialized.

#+NAME: functions
#+BEGIN_SRC c
void worgle_hashmap_init(worgle_hashmap *h)
{
    int n;
    h->nwords = 0;
    for(n = 0; n < 256; n++) {
        worgle_blocklist_init(&h->blk[n]);
    }
}
#+END_SRC
*** Freeing a Hash Map

Information allocated inside the hash map is freed using the function
=worgle_hashmap_free=.

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_hashmap_free(worgle_hashmap *h);
#+END_SRC

To free a hash map is to free each block list in the array.

#+NAME: functions
#+BEGIN_SRC c
void worgle_hashmap_free(worgle_hashmap *h)
{
    int n;
    for(n = 0; n < 256; n++) {
        worgle_blocklist_free(&h->blk[n]);
    }
}
#+END_SRC
*** Looking up an entry

A hashmap lookup can be done with the function =worgle_hashmap_find=.
This will attempt to look for a value with the key value =name=, and
save it in the block pointer =b=. If nothing is found, the function returns
FALSE (0). On success, TRUE (1).

#+NAME: function_declarations
#+BEGIN_SRC c
int worgle_hashmap_find(worgle_hashmap *h, worgle_string *name, worgle_block **b);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
<<hashmap_hasher>>
int worgle_hashmap_find(worgle_hashmap *h, worgle_string *name, worgle_block **b)
{
    int pos;
    worgle_blocklist *lst;
    int n;
    worgle_block *blk;
    pos = hash(name->str, name->size);
    lst = &h->blk[pos];

    blk = lst->head;
    for(n = 0; n < lst->nblocks; n++) {
        if(name->size == blk->name.size) {
            if(!strncmp(name->str, blk->name.str, name->size)) {
                *b = blk;
                return 1;
            }
        }
        blk = blk->nxt;
    }
    return 0;
}
#+END_SRC

Like any hashmap, a hashing algorithm is used to to compute which list to place
the entry in. This is one I've used on a number of projects now.

#+NAME: hashmap_hasher
#+BEGIN_SRC c
static int hash(const char *str, size_t size)
{
    unsigned int h = 5381;
    size_t i = 0;

    for(i = 0; i < size; i++) {
        h = ((h << 5) + h) ^ str[i];
        h %= 0x7FFFFFFF;
    }

    return h % 256;
}
#+END_SRC
*** Getting an entry

To "get" an entry means to return a block if it exists or not. Return
an entry that exists, or make a new one. This can be done with the function
=worgle_hashmap_get=.

#+NAME: function_declarations
#+BEGIN_SRC c
worgle_block * worgle_hashmap_get(worgle_hashmap *h, worgle_string *name);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
worgle_block * worgle_hashmap_get(worgle_hashmap *h, worgle_string *name)
{
    worgle_block *b;
    worgle_blocklist *lst;
    int pos;

    if(worgle_hashmap_find(h, name, &b)) return b;
    pos = hash(name->str, name->size);
    b = NULL;
    b = malloc(sizeof(worgle_block));
    worgle_block_init(b);
    b->name = *name;
    lst = &h->blk[pos];
    worgle_blocklist_append(lst, b);
    return b;
}
#+END_SRC
** File
A worgle file is an abstraction for a single file worgle will write to. Every
file has a filename, and a top-level code block. A worgle does not have a
filehandle. Files will only be created at the generation stage.
#+NAME: worgle_file
#+BEGIN_SRC c
typedef struct worgle_file {
    worgle_string filename;
    worgle_block *top;
    struct worgle_file *nxt;
} worgle_file;
#+END_SRC
*** Writing A File to a filehandle

A file is writen to a filehandle using the function =worgle_file_write=.
A hashmap is also required because it contains all the named code blocks
needed for any code expansion.

#+NAME:function_declarations
#+BEGIN_SRC c
int worgle_file_write(worgle_file *f, worgle_hashmap *h);
#+END_SRC

A filehandle is opened, the top-most code block is written using
=worgle_block_write=, and then the file is closed.

Because worgle strings are not zero terminated, they must be copied to a
temporary string buffer with a null terminator. Any filename greater than
127 characters will be truncated.

#+NAME: functions
#+BEGIN_SRC c
int worgle_file_write(worgle_file *f, worgle_hashmap *h)
{
    FILE *fp;
    char tmp[128];
    size_t n;
    size_t size;
    int rc;

    if(f->filename.size > 128) size = 127;
    else size = f->filename.size;
    for(n = 0; n < size; n++) tmp[n] = f->filename.str[n];
    tmp[size] = 0;

    fp = fopen(tmp, "w");

    rc = worgle_block_write(f->top, h, fp);

    fclose(fp);
    return rc;
}
#+END_SRC

** The File List

A file list is a linked list of worgle files.
#+NAME: worgle_filelist
#+BEGIN_SRC c
typedef struct {
    worgle_file *head;
    worgle_file *tail;
    int nfiles;
} worgle_filelist;
#+END_SRC
*** Initializing a file list

A file list is zeroed out and initialized using the function
=worgle_filelist_init=.

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_filelist_init(worgle_filelist *flist);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
void worgle_filelist_init(worgle_filelist *flist)
{
    flist->head = NULL;
    flist->tail = NULL;
    flist->nfiles = 0;
}
#+END_SRC

*** Freeing a file list

A filelist is freed using the function =worgle_filelist_free=.

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_filelist_free(worgle_filelist *flist);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
void worgle_filelist_free(worgle_filelist *flist)
{
    worgle_file *f;
    worgle_file *nxt;
    int n;
    f = flist->head;
    for(n = 0; n < flist->nfiles; n++) {
        nxt = f->nxt;
        free(f);
        f = nxt;
    }
}
#+END_SRC
*** Appending a file to a file list

A file is appended to the file list using the function =worgle_filelist_append=.
The name, as well as the well as the top-level code block are required here.

#+NAME: function_declarations
#+BEGIN_SRC c
void worgle_filelist_append(worgle_filelist *flist,
                           worgle_string *name,
                           worgle_block *top);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
void worgle_filelist_append(worgle_filelist *flist,
                           worgle_string *name,
                           worgle_block *top)
{
    worgle_file *f;
    f = malloc(sizeof(worgle_file));
    f->filename = *name;
    f->top = top;

    if(flist->nfiles == 0) {
        flist->head = f;
        flist->tail = f;
    }
    flist->tail->nxt = f;
    flist->tail = f;
    flist->nfiles++;
}
#+END_SRC
*** Writing a filelist to disk

A file list can be appended using the function =worgle_filelist_write=.

A hashmap containing all named code blocks all that is required.

#+NAME: function_declarations
#+BEGIN_SRC c
int worgle_filelist_write(worgle_filelist *flist, worgle_hashmap *h);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
int worgle_filelist_write(worgle_filelist *flist, worgle_hashmap *h)
{
    worgle_file *f;
    int n;

    f = flist->head;
    for(n = 0; n < flist->nfiles; n++) {
        if(!worgle_file_write(f, h)) return 0;
        f = f->nxt;
    }

    return 1;
}
#+END_SRC
